export default {
  data(){
    return{
      tableKey:0,
      resizeMode:false,
      startPoint:null,
      endPoint:null,
      selectName:null,
      selectedIndexs:[],
      selected:[],
      dragStatus:false,
      currentOffset:0,
      lazyLoadFlag:false,
      tableTabs:[],
      listAllSelected:false,
      tableOrder:this.ordering,
      currentTab:"main",
      dataAllSelected:false,
      currentColumns: this.columns && this.columns.length ? this.columns : this.defaultColumns,
      currentActions:this.actions && this.actions.length ? this.actions : this.defaultActions,
      settings:{
        tableBackgroundColor:"#fff",
        tableTextColor:"#343A40",
        headerBackgroundColor:"#F7F9F9",
        headerTextColor: "#343A40",
        topbarHeight:"28px",
        headerHeight:"30px",
        rowHeight:null,
        rowHoverStatus:true,
        rowSelectedColorStatus:true,
        rowScrollStatus:false,
        selectedTabStatus:true,
        rowBorderStatus:true,
        rowHoverColor:"#EEEEEE",
        rowSelectedColor:"#81D4FA",
        rowScrollSize:2,
        rowBorderColor:"#EEEEEE",
        rowBorderSize:1,
        tableBodyHeight:"65vh",
        paginationHeight:"35px",
        colResize:false,
        shortcutSelectAllToggle:"alt+q",
        shortcutSelectFilteredAll:"shift+f",
      }
    }
  }
}
